### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by Kaweees** [Reaper3629/Reaper3629.github.io#1]
Rename this repo to Reaper3629.github.io if you plan on hosting this on [GitHub Pages](https://pages.github.com) or the name of your website domain or portfolio. [andresh.dev](https://andresh.dev) has a nice spin to it, I would suggest [porkbun](https://porkbun.com) to buy it should you choose to.

**Comment by andres-perez0** [comment]
I've renamed the repository. Thank you for your comment! I'll look into GitHub Pages for now and then assess the feasibility of purchasing a domain. Your help is greatly appreciated!
